### PR TITLE
Irc and stuff

### PR DESCRIPTION
**Pull request by Baughn**
Some testing with Chrome shows that this cuts about 10% off the loading time. Which isn't much, but if you control your own webserver, you can save far more by enabling HTTP2.

(While you're at it, let's talk about HTTPS. Let's Encrypt has launched, so there's really no excuse anymore.)

Otherwise, this just adds an "IRC" tab so it'll be easier for people to find us.

### CODE REVIEW

**Comment by Baughn** [comment]
Urgh, I just noticed that the diffs look *absolutely awful*. So much pointless whitespace.

If you don't want to merge, I understand. I'll see if I can clean it up.

**Comment by metc** [comment]
Thank you @Baughn for this PR. A Googler should use WebP instead or PNG, shouldn't you ? :smiley: 

We choose to host the website on Github, so we cannot change the server settings such as Gzip compression, etc.
For HTTPS, a solution would be to use CloudFlare which also give free SSL certificates ([as described here](https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html)). Any idea ?
Using HTTPS by default would be great. What is your opinion ?

I am trying to serve your changes locally. Do I need to install `rmagick` manually ? Will be this plugin supported on Github pages ?

**Comment by Baughn** [comment]
I'd love to use WebP, but it isn't supported very many places, so PNG it is.

Cloudflare would handle HTTPS and HTTP2 just fine. Do you need help setting it up?

As for Jekyll... hmm. I needed to 'gem installl jekyll-responsive_images' locally, and I didn't realize at the time that you even used GitHub pages, much less that it'd build-on-push and so forth. I may need to go back to the drawing board on this one, if you want to keep using it; I like having more control over my own sites, so it didn't occur to me that you'd be doing it that way.

OTOH, it *is* a static site generator, so in the limit you could probably build locally and then push? That'd be a bit more work, though.

**Comment by Baughn** [comment]
Managed to clean up the whitespace, at least. (Never mind that Github doesn't do well at diffing reindents.)

**Comment by metc** [comment]
Add `?w=1` to the URL to see the diff with white space ignored. Thanks to clean up this.

I had to install `ImageMagick` manually on my Windows PC to see your changes locally. I like the idea to resize the assets and use the appropriate size automatically, but now both `http://127.0.0.1:4000/assets/resized/700/ELN_PPICTSET1_0002F.JPG` and `http://127.0.0.1:4000/screenshots/ELN_PPICTSET1_0002F.JPG` images are loaded ? Is this the correct behavior ?

**Comment by Baughn** [comment]
That's not correct behaviour... and it also isn't how Chrome or Firefox behaves for me. Which browser are you running on? Oh, and are those both loaded at the same time?

Imgset isn't supported by IE, but I didn't expect it'd do that. The non-assets version of the screenshots dir exists only for the src parameter, which should be ignored in favor of srcset on supporting browsers.

**Comment by Baughn** [comment]
Actually, I was missing a very important attribute for using it. Try now!

**Comment by metc** [comment]
I use the network analyser from the dev tools in Chrome 47. For instance, I see that these two images are loaded:
- http://127.0.0.1:4000/assets/resized/700/ELN_PPICTSET2_0001SMALL.JPG
- http://127.0.0.1:4000/screenshots/ELN_PPICTSET2_0001SMALL.JPG

The resized asset should replace the screenshot image, I am right ? Can you check this behavior on your side ?

**Comment by Baughn** [comment]
The screenshot (original) version should never be loaded at all, and in my browser it isn't.

Try loading with 'disable cache' checked on the network pane? AIUI, if there's a larger version in your cache it'll use that instead, and it seems that there's some edge case when switching from src to srcset.

**Comment by metc** [comment]
Ok I see, it is fine now. Thank you.

**Comment by Baughn** [comment]
I changed up the image-set config a bit again, adding a lower-quality, 350px version for absolutely minimal size.

Then I opened it on my phone, set to 2G, and found to my joy that it picked that one instead of the usual 1400px version. It still wasn't exactly snappy, but it loaded in half a minute instead of half an hour.

**Comment by metc** [comment]
Unfortunately, the `jekyll-responsive-image` plugin is not available on Github Pages. Available dependency are available here: https://pages.github.com/versions/

I will build the website locally and then push it.

**Comment by Baughn** [comment]
You could automate that with a very small cron script, I suppose.

**Comment by cm0x4D** [comment]
Sounds like a job for travis...

**Comment by Baughn** [comment]
Well, if you want automated testing. There's something to be said for that as well, but I do enjoy my very small shell scripts.

```
*/10 * * * * ~/update-web.sh
```

```bash
#!/bin/bash

set -e

rl() {
  git reflog | awk '{print $1}'
}

cd ~/electrical-age.github.io
PRE=$(rl)
git pull
POST=$(rl)

if [[ $PRE != $POST ]]; then
  jekyll build
  rsync -a _site/ $TARGET:
fi
```

**Comment by metc** [comment]
Thank you @Baughn but I will use Travis for such job. I will add it soon.

**Comment by metc** [comment]
I spoke with @Dolu1990 and for now we had the IRC menu as an external link.
I removed the tabs for now, but we will add them back when we have more content to display. Thank you again for your contribution.

**Comment by metc** [comment]
Travis works now !

**Pull request merged**
